version: 2

sources:
  - name: raw
    database: dbt-tutorial
    schema: jaffle_shop
    tables:
      - name: customers
      - name: orders
  - name: stripe
    database: dbt-tutorial
    schema: stripe
    tables:
      - name: payment
